"""The full hook surface upstream NMS.py supported on 4.13, gated per build.

AUTO-GENERATED by tools/legacy_re/generate_hook_stubs.py -- do not edit by hand.
Prototypes derive from the 4.13 PDB; pointer/reference/struct arguments are raw
c_uint64 addresses. Whether each hook works in the running build is data-driven from
offsets.json (see nmspy.data.offsets.availability): located functions hook normally,
the rest degrade to warning stubs. Hand-written classes in nmspy.data.types inherit
these as mixins and refine them.
"""

from ctypes import c_bool, c_double, c_float, c_int8, c_int16, c_int32, c_int64, c_uint8, c_uint16, c_uint32, c_uint64  # noqa: E501

from nmspy.data.offsets import legacy_hook

@legacy_hook("GenerateModdedFilepath", static=True)
def GenerateModdedFilepath():
    ...  # modern signature unknown

@legacy_hook("MiniDumpFunction", static=True)
def MiniDumpFunction():
    ...  # modern signature unknown

@legacy_hook("nvgArc", static=True)
def nvgArc() -> c_uint64:
    ...  # modern signature unknown

@legacy_hook("nvgEllipse", static=True)
def nvgEllipse() -> c_uint64:
    ...  # modern signature unknown

@legacy_hook("nvgFill", static=True)
def nvgFill() -> c_uint64:
    ...  # modern signature unknown

@legacy_hook("nvgRect", static=True)
def nvgRect() -> c_uint64:
    ...  # modern signature unknown

@legacy_hook("nvgText", static=True)
def nvgText() -> c_uint64:
    ...  # modern signature unknown

@legacy_hook("nvgTextBox", static=True)
def nvgTextBox() -> c_uint64:
    ...  # modern signature unknown

class EgInstancedModelExtension:
    class cEgInstancedMeshNode:
        @legacy_hook("EgInstancedModelExtension::cEgInstancedMeshNode::RenderAsync")
        def RenderAsync(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_int32, a3: c_bool, a4: c_uint64, a5: c_bool, a6: c_bool, a7: c_uint64, a8: c_uint64):
            """``void EgInstancedModelExtension::cEgInstancedMeshNode::RenderAsync(cEgRenderQueueBuffer &, union TkID<128> const&, int, bool, RenderingOrder::List, bool, bool, cEgFrustum const *, cEgThreadableRenderCall *)``"""
            ...

class Engine:
    @legacy_hook("Engine::AddGroupNode", static=True)
    def AddGroupNode(a0: c_uint64, a1: c_uint64) -> c_uint64:
        """``TkHandle Engine::AddGroupNode(TkHandle, char const *)``"""
        ...
    @legacy_hook("Engine::AddNodes", static=True)
    def AddNodes(a0: c_uint64, a1: c_uint64) -> c_uint64:
        """``TkHandle Engine::AddNodes(TkHandle, TkStrongType<int,TkStrongTypeIDs::TkResHandleID>)``"""
        ...
    @legacy_hook("Engine::AddResource", static=True)
    def AddResource():
        ...  # modern signature unknown
    @legacy_hook("Engine::GetModelNode", static=True)
    def GetModelNode(a0: c_uint64) -> c_uint64:
        """``TkHandle Engine::GetModelNode(TkHandle)``"""
        ...
    @legacy_hook("Engine::GetNodeAbsoluteTransMatrix", static=True)
    def GetNodeAbsoluteTransMatrix(a0: c_uint64, a1: c_uint64):
        """``void Engine::GetNodeAbsoluteTransMatrix(TkHandle, cTkMatrix34 *)``"""
        ...
    @legacy_hook("Engine::GetNodeName", static=True)
    def GetNodeName():
        ...  # modern signature unknown
    @legacy_hook("Engine::GetNodeNumChildren", static=True)
    def GetNodeNumChildren(a0: c_uint64) -> c_int32:
        """``int Engine::GetNodeNumChildren(TkHandle)``"""
        ...
    @legacy_hook("Engine::GetNodeParent", static=True)
    def GetNodeParent(a0: c_uint64) -> c_uint64:
        """``TkHandle Engine::GetNodeParent(TkHandle)``"""
        ...
    @legacy_hook("Engine::GetNodeType", static=True)
    def GetNodeType(a0: c_uint64) -> c_int32:
        """``int Engine::GetNodeType(TkHandle)``"""
        ...
    @legacy_hook("Engine::GetRenderBufferTexture", static=True)
    def GetRenderBufferTexture(a0: c_uint64, a1: c_int32) -> c_uint64:
        """``void * Engine::GetRenderBufferTexture(TkStrongType<int,TkStrongTypeIDs::TkResHandleID>, int)``"""
        ...
    @legacy_hook("Engine::GetResourceHandleForNode", static=True)
    def GetResourceHandleForNode(a0: c_uint64) -> c_uint64:
        """``TkStrongType<int,TkStrongTypeIDs::TkResHandleID> Engine::GetResourceHandleForNode(TkHandle)``"""
        ...
    @legacy_hook("Engine::GetTexture", static=True)
    def GetTexture(a0: c_uint64) -> c_uint64:
        """``void * Engine::GetTexture(TkStrongType<int,TkStrongTypeIDs::TkResHandleID>)``"""
        ...
    @legacy_hook("Engine::Initialise", static=True)
    def Initialise() -> c_bool:
        """``bool Engine::Initialise()``"""
        ...
    @legacy_hook("Engine::SetMaterialSampler", static=True)
    def SetMaterialSampler(a0: c_uint64, a1: c_uint64, a2: c_uint64) -> c_bool:
        """``bool Engine::SetMaterialSampler(TkStrongType<int,TkStrongTypeIDs::TkResHandleID>, char const *, TkStrongType<int,TkStrongTypeIDs::TkResHandleID>)``"""
        ...
    @legacy_hook("Engine::SetMaterialUniformArray", static=True)
    def SetMaterialUniformArray(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_int32) -> c_bool:
        """``bool Engine::SetMaterialUniformArray(TkStrongType<int,TkStrongTypeIDs::TkResHandleID>, char const *, float const *, int)``"""
        ...
    @legacy_hook("Engine::SetOption", static=True)
    def SetOption(a0: c_uint64, a1: c_float) -> c_bool:
        """``bool Engine::SetOption(EgOptions::List, float)``"""
        ...
    @legacy_hook("Engine::SetUniformArrayDefaultMultipleShaders", static=True)
    def SetUniformArrayDefaultMultipleShaders(a0: c_uint64, a1: c_int32, a2: c_uint64, a3: c_uint64, a4: c_int32) -> c_int32:
        """``int Engine::SetUniformArrayDefaultMultipleShaders(TkStrongType<int,TkStrongTypeIDs::TkResHandleID> *, int, char const *, float const *, int)``"""
        ...
    @legacy_hook("Engine::ShiftAllTransformsForNode", static=True)
    def ShiftAllTransformsForNode(a0: c_uint64, a1: c_uint64):
        """``void Engine::ShiftAllTransformsForNode(TkHandle, cTkVector3 const&)``"""
        ...

class GeometryStreaming:
    class cEgGeometryStreamer:
        @legacy_hook("GeometryStreaming::cEgGeometryStreamer::FindVertexBufferIndexByHash", static=True)
        def FindVertexBufferIndexByHash():
            ...  # modern signature unknown
        @legacy_hook("GeometryStreaming::cEgGeometryStreamer::GetVertexBufferByIndex", static=True)
        def GetVertexBufferByIndex():
            ...  # modern signature unknown
        @legacy_hook("GeometryStreaming::cEgGeometryStreamer::OnBufferLoadFinish")
        def OnBufferLoadFinish(self, this: c_uint64, a0: c_uint64):
            """``void GeometryStreaming::cEgGeometryStreamer::OnBufferLoadFinish(void *)``"""
            ...
        @legacy_hook("GeometryStreaming::cEgGeometryStreamer::RequestStream")
        def RequestStream(self, this: c_uint64, a0: c_uint64):
            """``void GeometryStreaming::cEgGeometryStreamer::RequestStream(cTkResourceDescriptor const *)``"""
            ...

    class cEgStreamRequests:
        @legacy_hook("GeometryStreaming::cEgStreamRequests::ProcessOnlyStreamRequests")
        def ProcessOnlyStreamRequests(self, this: c_uint64, a0: c_double):
            """``void GeometryStreaming::cEgStreamRequests::ProcessOnlyStreamRequests(double)``"""
            ...

class SolarQueryResult:
    @legacy_hook("SolarQueryResult::ComputeLightyearDistanceBetweenSolarSystems", static=True)
    def ComputeLightyearDistanceBetweenSolarSystems(a0: c_uint64, a1: c_uint64) -> c_float:
        """``float SolarQueryResult::ComputeLightyearDistanceBetweenSolarSystems(SolarQueryResult const&, SolarQueryResult const&)``"""
        ...

class XMLNode:
    @legacy_hook("XMLNode::writeToFile")
    def writeToFile(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_int8) -> c_uint64:
        """``XMLError XMLNode::writeToFile(char const *, char const *, char)``"""
        ...

class cEgCodeResource:
    @legacy_hook("cEgCodeResource::Load")
    def Load(self, this: c_uint64, a0: c_uint64, a1: c_int32) -> c_bool:
        """``bool cEgCodeResource::Load(char const *, int)``"""
        ...

class cEgDrawGeometry:
    @legacy_hook("cEgDrawGeometry::Draw", static=True)
    def Draw(a0: c_uint64):
        """``void cEgDrawGeometry::Draw(void *)``"""
        ...

class cEgGeometryResource:
    @legacy_hook("cEgGeometryResource::CloneInternal")
    def CloneInternal(self, this: c_uint64, a0: c_uint64):
        """``void cEgGeometryResource::CloneInternal(cTkResource const *)``"""
        ...
    @legacy_hook("cEgGeometryResource::CloneOriginalVertDataToIndex")
    def CloneOriginalVertDataToIndex(self, this: c_uint64, a0: c_int32):
        """``void cEgGeometryResource::CloneOriginalVertDataToIndex(int)``"""
        ...
    @legacy_hook("cEgGeometryResource::CreateVertexInfoForHash")
    def CreateVertexInfoForHash(self, this: c_uint64, a0: c_uint64):
        """``void cEgGeometryResource::CreateVertexInfoForHash(unsigned __int64)``"""
        ...
    @legacy_hook("cEgGeometryResource::Load")
    def Load(self, this: c_uint64, a0: c_uint64, a1: c_int32) -> c_bool:
        """``bool cEgGeometryResource::Load(char const *, int)``"""
        ...
    @legacy_hook("cEgGeometryResource::ParseData")
    def ParseData(self, this: c_uint64, a0: c_uint64) -> c_bool:
        """``bool cEgGeometryResource::ParseData(cTkGeometryData &)``"""
        ...
    @legacy_hook("cEgGeometryResource::cEgGeometryResource")
    def cEgGeometryResource(self, this: c_uint64, a0: c_uint64, a1: c_int32, a2: c_uint64) -> c_uint64:
        """``cEgGeometryResource::cEgGeometryResource(std::basic_string<char,std::char_traits<char>,TkSTLAllocatorShim<char,1,-1> > const&, int, cTkResourceDescriptor const *)``"""
        ...

class cEgMaterialResource:
    @legacy_hook("cEgMaterialResource::ParseNode")
    def ParseNode(self, this: c_uint64, a0: c_uint64) -> c_bool:
        """``bool cEgMaterialResource::ParseNode(cTkMaterialData &)``"""
        ...

class cEgMeshNode:
    @legacy_hook("cEgMeshNode::ParsingFunc", static=True)
    def ParsingFunc(a0: c_uint64, a1: c_uint64, a2: c_int32) -> c_uint64:
        """``cEgSceneNodeTemplate * cEgMeshNode::ParsingFunc(cTkDynamicArray<cTkSceneNodeAttributeData> const&, cTkResourceDescriptor *, int)``"""
        ...

class cEgModelNode:
    @legacy_hook("cEgModelNode::Animate")
    def Animate(self, this: c_uint64):
        """``void cEgModelNode::Animate()``"""
        ...
    @legacy_hook("cEgModelNode::UpdateGeometry")
    def UpdateGeometry(self, this: c_uint64) -> c_bool:
        """``bool cEgModelNode::UpdateGeometry()``"""
        ...

class cEgModules:
    @legacy_hook("cEgModules::Initialise", static=True)
    def Initialise():
        """``void cEgModules::Initialise()``"""
        ...

class cEgRenderer:
    @legacy_hook("cEgRenderer::DrawMeshes", static=True)
    def DrawMeshes(a0: c_uint64, a1: c_uint64, a2: c_int32, a3: c_bool, a4: c_uint64, a5: c_bool, a6: c_bool, a7: c_uint64, a8: c_uint64):
        """``void cEgRenderer::DrawMeshes(cEgRenderQueueBuffer &, union TkID<128> const&, int, bool, RenderingOrder::List, bool, bool, cEgFrustum const&, cEgThreadableRenderCall *)``"""
        ...
    @legacy_hook("cEgRenderer::DrawRenderables")
    def DrawRenderables(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64, a4: c_uint64, a5: c_int32, a6: c_bool, a7: c_uint64, a8: c_bool, a9: c_int32, a10: c_int32, a11: c_uint64, a12: c_bool, a13: c_bool):
        """``void cEgRenderer::DrawRenderables(cEgRenderQueue &, cEgFrustum const&, union TkID<128> const&, std::basic_string<char,std::char_traits<char>,std::allocator<char> > const&, union TkID<128> const&, int, bool, RenderingOrder::List, bool, int, int, cEgThreadableRenderCall *, bool, bool)``"""
        ...
    @legacy_hook("cEgRenderer::SetupMeshGeometry", static=True)
    def SetupMeshGeometry(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64, a4: c_bool, a5: c_uint64, a6: c_uint64) -> c_bool:
        """``bool cEgRenderer::SetupMeshGeometry(cEgMeshNode *, cEgGeometryResource *, unsigned int &, cTkVertexLayoutRT const * &, bool, cTkRenderStateCache *, cEgThreadableRenderCall *)``"""
        ...
    @legacy_hook("cEgRenderer::SetupMeshMaterial", static=True)
    def SetupMeshMaterial(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_int32, a4: c_uint64, a5: c_uint64, a6: c_uint64, a7: c_uint64, a8: c_uint64, a9: c_float, a10: c_int32, a11: c_uint64, a12: c_uint64, a13: c_int32, a14: c_bool, a15: c_uint64, a16: c_bool, a17: c_uint64) -> c_bool:
        """``bool cEgRenderer::SetupMeshMaterial(cEgMeshNode *, cEgMaterialResource *, TkIDHashed<128> const&, int, cTkMatrix34 const&, cTkMatrix34 const&, cTkMatrix44 const&, cTkMatrix44 const&, cTkMatrix44 const&, float, int, cTkVector4 *, cTkVector4 *, int, bool, cEgThreadableRenderCall *, bool, cEgShaderUniformBufferBinding *)``"""
        ...

class cEgRendererBase:
    @legacy_hook("cEgRendererBase::ApplyVertexLayout")
    def ApplyVertexLayout(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_int32) -> c_bool:
        """``bool cEgRendererBase::ApplyVertexLayout(cTkVertexLayoutRT const&, cTkShader const&, cEgThreadableRenderCall *, int)``"""
        ...

class cEgResource:
    @legacy_hook("cEgResource::Load")
    def Load(self, this: c_uint64, a0: c_uint64, a1: c_int32) -> c_bool:
        """``bool cEgResource::Load(char const *, int)``"""
        ...

class cEgSceneGraphResource:
    @legacy_hook("cEgSceneGraphResource::ParseData")
    def ParseData(self, this: c_uint64, a0: c_uint64, a1: c_uint64) -> c_bool:
        """``bool cEgSceneGraphResource::ParseData(cTkSceneNodeData &, cEgSceneNodeTemplate *)``"""
        ...

class cEgSceneNodeData:
    @legacy_hook("cEgSceneNodeData::SetRelativeTransform")
    def SetRelativeTransform(self, this: c_uint64, a0: c_uint64, a1: c_uint64):
        """``void cEgSceneNodeData::SetRelativeTransform(TkHandle, cTkMatrix34 const&)``"""
        ...

class cEgTextureResource:
    @legacy_hook("cEgTextureResource::Load")
    def Load(self, this: c_uint64, a0: c_uint64, a1: c_int32) -> c_bool:
        """``bool cEgTextureResource::Load(char const *, int)``"""
        ...
    @legacy_hook("cEgTextureResource::LoadFromDds")
    def LoadFromDds(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_int32, a3: c_int32, a4: c_int32, a5: c_uint64, a6: c_int32, a7: c_int32) -> c_bool:
        """``bool cEgTextureResource::LoadFromDds(char const *, char const *, int, int, int, unsigned int *, int, int)``"""
        ...

class cGcApplication:
    @legacy_hook("cGcApplication::Construct")
    def Construct(self, this: c_uint64):
        """``void cGcApplication::Construct()``"""
        ...
    @legacy_hook("cGcApplication::Update")
    def Update(self, this: c_uint64):
        """``void cGcApplication::Update()``"""
        ...

    class Data:
        @legacy_hook("cGcApplication::Data::Data")
        def Data(self, this: c_uint64) -> c_uint64:
            """``cGcApplication::Data::Data()``"""
            ...

class cGcApplicationBootState:
    @legacy_hook("cGcApplicationBootState::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcApplicationBootState::Update(float)``"""
        ...

class cGcApplicationGameModeSelectorState:
    @legacy_hook("cGcApplicationGameModeSelectorState::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcApplicationGameModeSelectorState::Update(float)``"""
        ...

class cGcApplicationLocalLoadState:
    @legacy_hook("cGcApplicationLocalLoadState::GetRespawnReason")
    def GetRespawnReason(self, this: c_uint64) -> c_uint64:
        """``cGcPlayerRespawn::RespawnReason cGcApplicationLocalLoadState::GetRespawnReason()``"""
        ...

class cGcBaseBuildingManager:
    @legacy_hook("cGcBaseBuildingManager::AddHUDMarker")
    def AddHUDMarker(self, this: c_uint64, a0: c_int32, a1: c_uint64, a2: c_int32, a3: c_uint64):
        """``void cGcBaseBuildingManager::AddHUDMarker(cGcMarkerPoint::eType, cTkPhysRelMat34 const&, int, char const *)``"""
        ...
    @legacy_hook("cGcBaseBuildingManager::GetBaseBuildingRootMatrix")
    def GetBaseBuildingRootMatrix(self, this: c_uint64, a0: c_uint64, a1: c_uint64) -> c_uint64:
        """``cTkPhysRelMat34 cGcBaseBuildingManager::GetBaseBuildingRootMatrix(BaseIndex, unsigned __int64)``"""
        ...
    @legacy_hook("cGcBaseBuildingManager::GetBaseRootNode")
    def GetBaseRootNode(self, this: c_uint64, a0: c_uint64, a1: c_bool) -> c_uint64:
        """``TkHandle cGcBaseBuildingManager::GetBaseRootNode(BaseIndex, bool)``"""
        ...
    @legacy_hook("cGcBaseBuildingManager::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcBaseBuildingManager::Update(float)``"""
        ...

class cGcBaseSearch:
    @legacy_hook("cGcBaseSearch::FindNearestBaseInCurrentSystem", static=True)
    def FindNearestBaseInCurrentSystem(a0: c_uint64, a1: c_int32) -> c_uint64:
        """``BaseIndex cGcBaseSearch::FindNearestBaseInCurrentSystem(cTkVector3 const&, ePersistentBaseTypes)``"""
        ...

class cGcBeamEffect:
    @legacy_hook("cGcBeamEffect::Prepare")
    def Prepare(self, this: c_uint64):
        """``void cGcBeamEffect::Prepare()``"""
        ...

class cGcBinoculars:
    @legacy_hook("cGcBinoculars::GetRange")
    def GetRange(self, this: c_uint64) -> c_float:
        """``float cGcBinoculars::GetRange()``"""
        ...
    @legacy_hook("cGcBinoculars::PopulateDiscoveryInfo")
    def PopulateDiscoveryInfo(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_bool, a4: c_bool):
        """``void cGcBinoculars::PopulateDiscoveryInfo(DiscoveryResolver::DiscoveryInfo &, TkHandle, cTkAttachmentPtr, bool, bool)``"""
        ...
    @legacy_hook("cGcBinoculars::SetMarker")
    def SetMarker(self, this: c_uint64):
        """``void cGcBinoculars::SetMarker()``"""
        ...
    @legacy_hook("cGcBinoculars::UpdateRayCasts")
    def UpdateRayCasts(self, this: c_uint64, a0: c_uint64):
        """``void cGcBinoculars::UpdateRayCasts(cTkContactPoint &)``"""
        ...
    @legacy_hook("cGcBinoculars::UpdateScanBarProgress")
    def UpdateScanBarProgress(self, this: c_uint64, a0: c_float):
        """``void cGcBinoculars::UpdateScanBarProgress(float)``"""
        ...
    @legacy_hook("cGcBinoculars::UpdateTarget")
    def UpdateTarget(self, this: c_uint64, a0: c_float):
        """``void cGcBinoculars::UpdateTarget(float)``"""
        ...

class cGcBuilding:
    @legacy_hook("cGcBuilding::DestroyIntersectingVolcanoes")
    def DestroyIntersectingVolcanoes(self, this: c_uint64):
        """``void cGcBuilding::DestroyIntersectingVolcanoes()``"""
        ...
    @legacy_hook("cGcBuilding::Visited")
    def Visited(self, this: c_uint64, a0: c_bool):
        """``void cGcBuilding::Visited(bool)``"""
        ...

class cGcCreatureComponent:
    @legacy_hook("cGcCreatureComponent::Prepare")
    def Prepare(self, this: c_uint64):
        """``void cGcCreatureComponent::Prepare()``"""
        ...

class cGcDestructableComponent:
    @legacy_hook("cGcDestructableComponent::Destroy")
    def Destroy(self, this: c_uint64, a0: c_int32, a1: c_uint64):
        """``void cGcDestructableComponent::Destroy(eDestroyedBy, cTkUserIdBase<cTkFixedString<64,char> > const&)``"""
        ...

class cGcDiscoveryManager:
    @legacy_hook("cGcDiscoveryManager::SubmitDiscoveryData")
    def SubmitDiscoveryData(self, this: c_uint64, a0: c_uint64, a1: c_uint64) -> c_bool:
        """``bool cGcDiscoveryManager::SubmitDiscoveryData(cGcDiscoveryData const&, bool *)``"""
        ...

class cGcEcosystem:
    @legacy_hook("cGcEcosystem::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcEcosystem::Update(float)``"""
        ...

class cGcEnvironment:
    @legacy_hook("cGcEnvironment::Update")
    def Update(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cGcEnvironment::UpdateRender")
    def UpdateRender(self, this: c_uint64):
        """``void cGcEnvironment::UpdateRender()``"""
        ...

class cGcFishLaser:
    @legacy_hook("cGcFishLaser::OnModeChanged")
    def OnModeChanged(self, this: c_uint64):
        ...  # modern signature unknown

class cGcFishManager:
    @legacy_hook("cGcFishManager::SetFishing")
    def SetFishing(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cGcFishManager::Update")
    def Update(self, this: c_uint64):
        ...  # modern signature unknown

class cGcFishingData:
    @legacy_hook("cGcFishingData::GetRandomFish")
    def GetRandomFish(self, this: c_uint64):
        ...  # modern signature unknown

class cGcFrontendManager:
    @legacy_hook("cGcFrontendManager::QueueFrontendPage")
    def QueueFrontendPage(self, this: c_uint64, a0: c_int32, a1: c_float, a2: c_uint64):
        """``void cGcFrontendManager::QueueFrontendPage(eFrontendPage, float, cGcInteractionComponent *)``"""
        ...
    @legacy_hook("cGcFrontendManager::cGcFrontendManager")
    def cGcFrontendManager(self, this: c_uint64) -> c_uint64:
        """``cGcFrontendManager::cGcFrontendManager()``"""
        ...

class cGcFrontendPageClaimBase:
    @legacy_hook("cGcFrontendPageClaimBase::DoBaseClaimOptions", static=True)
    def DoBaseClaimOptions(a0: c_uint64, a1: c_uint64, a2: c_int32, a3: c_bool, a4: c_uint64):
        """``void cGcFrontendPageClaimBase::DoBaseClaimOptions(cGcFrontendPage *, std::array<cGcNGuiLayer *,5>, ePersistentBaseTypes, bool, BaseIndex)``"""
        ...

class cGcFrontendPageDiscovery:
    @legacy_hook("cGcFrontendPageDiscovery::DoDiscoveryView", static=True)
    def DoDiscoveryView(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64):
        """``void cGcFrontendPageDiscovery::DoDiscoveryView(cGcFrontendPage *, cGcDiscoveryPageData &, cGcFrontendTextInput &, cGcFrontendModelRenderer &)``"""
        ...
    @legacy_hook("cGcFrontendPageDiscovery::GetDiscoveryHintString")
    def GetDiscoveryHintString(self, this: c_uint64, a0: c_int32, a1: c_int32, a2: c_int32, a3: c_int32, a4: c_int32) -> c_uint64:
        """``cTkFixedString<64,char> cGcFrontendPageDiscovery::GetDiscoveryHintString(eTileType, eCreatureType, eRarity, eCreatureActiveTime, eCreatureHemiSphere)``"""
        ...

class cGcFrontendPageFunctions:
    @legacy_hook("cGcFrontendPageFunctions::DoEmptySlotPopup", static=True)
    def DoEmptySlotPopup(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64, a4: c_uint64):
        """``void cGcFrontendPageFunctions::DoEmptySlotPopup(cGcFrontendPage *, cGcNGuiLayer *, std::vector<ePopupAction,TkSTLAllocatorShim<ePopupAction,4,-1> > &, cGcInventoryIndex const&, cGcInventoryStore *)``"""
        ...
    @legacy_hook("cGcFrontendPageFunctions::SetEmptySlotBackground", static=True)
    def SetEmptySlotBackground(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_bool):
        """``void cGcFrontendPageFunctions::SetEmptySlotBackground(cGcFrontendPage *, cGcNGuiLayer *, InventoryChoice, bool)``"""
        ...
    @legacy_hook("cGcFrontendPageFunctions::SetPopupBasics", static=True)
    def SetPopupBasics(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64, a4: c_uint64, a5: c_uint64, a6: c_uint64, a7: c_uint64, a8: c_bool, a9: c_int32, a10: c_uint64) -> c_uint64:
        """``cGcNGuiLayer * cGcFrontendPageFunctions::SetPopupBasics(cGcNGuiLayer *, char const *, cTkColour const&, char const *, char const *, char const *, char const *, char const *, bool, int, union TkID<128> const&)``"""
        ...

class cGcFrontendPagePortalRunes:
    @legacy_hook("cGcFrontendPagePortalRunes::CheckUAIsValid", static=True)
    def CheckUAIsValid(a0: c_uint64, a1: c_uint64, a2: c_bool) -> c_bool:
        """``bool cGcFrontendPagePortalRunes::CheckUAIsValid(unsigned __int64, unsigned __int64 &, bool)``"""
        ...
    @legacy_hook("cGcFrontendPagePortalRunes::DoInteraction")
    def DoInteraction(self, this: c_uint64, a0: c_uint64):
        """``void cGcFrontendPagePortalRunes::DoInteraction(cGcFrontendPage *)``"""
        ...

class cGcGalaxyAttributeGenerator:
    @legacy_hook("cGcGalaxyAttributeGenerator::ClassifyStarKeyAttributes", static=True)
    def ClassifyStarKeyAttributes(a0: c_uint64, a1: c_uint64):
        """``void cGcGalaxyAttributeGenerator::ClassifyStarKeyAttributes(unsigned __int64, cGcGalaxyAttributeGenerator::StarSystemKeyAttributes &)``"""
        ...
    @legacy_hook("cGcGalaxyAttributeGenerator::ClassifyStarKeyAttributes", static=True)
    def ClassifyStarKeyAttributes_2(a0: c_uint64, a1: c_uint16, a2: c_uint64, a3: c_uint64, a4: c_uint64):
        """``void cGcGalaxyAttributeGenerator::ClassifyStarKeyAttributes(cTkParallelRNG &, unsigned short, cGcGalaxyVoxelAttributesData &, cGcGalaxyAttributeGenerator::StarSystemKeyAttributes &, unsigned __int64)``"""
        ...
    @legacy_hook("cGcGalaxyAttributeGenerator::ClassifyStarSystem", static=True)
    def ClassifyStarSystem(a0: c_uint64, a1: c_uint64):
        """``void cGcGalaxyAttributeGenerator::ClassifyStarSystem(unsigned __int64, cGcGalaxyStarAttributesData &)``"""
        ...
    @legacy_hook("cGcGalaxyAttributeGenerator::ClassifyVoxel", static=True)
    def ClassifyVoxel(a0: c_uint64, a1: c_uint64):
        """``void cGcGalaxyAttributeGenerator::ClassifyVoxel(cGcGalacticVoxelCoordinate const&, cGcGalaxyVoxelAttributesData &)``"""
        ...

class cGcGalaxyAttributesAtAddress:
    @legacy_hook("cGcGalaxyAttributesAtAddress::Classify")
    def Classify(self, this: c_uint64, a0: c_uint64):
        """``void cGcGalaxyAttributesAtAddress::Classify(unsigned __int64)``"""
        ...

class cGcGalaxyMap:
    class Data:
        @legacy_hook("cGcGalaxyMap::Data::DoSolarPopup")
        def DoSolarPopup(self, this: c_uint64, a0: c_uint64):
            """``void cGcGalaxyMap::Data::DoSolarPopup(SolarQueryResult const&)``"""
            ...
        @legacy_hook("cGcGalaxyMap::Data::RenderNVG")
        def RenderNVG(self, this: c_uint64):
            """``void cGcGalaxyMap::Data::RenderNVG()``"""
            ...
        @legacy_hook("cGcGalaxyMap::Data::Update")
        def Update(self, this: c_uint64, a0: c_float):
            """``void cGcGalaxyMap::Data::Update(float)``"""
            ...

class cGcGalaxyMapUI:
    class SolarInfoPanel:
        @legacy_hook("cGcGalaxyMapUI::SolarInfoPanel::UpdatePanelUI")
        def UpdatePanelUI(self, this: c_uint64):
            """``void cGcGalaxyMapUI::SolarInfoPanel::UpdatePanelUI()``"""
            ...

class cGcGalaxyStarAttributesData:
    @legacy_hook("cGcGalaxyStarAttributesData::SetDefaults")
    def SetDefaults(self, this: c_uint64):
        """``void cGcGalaxyStarAttributesData::SetDefaults()``"""
        ...

class cGcGalaxyVoxelAttributesData:
    @legacy_hook("cGcGalaxyVoxelAttributesData::SetDefaults")
    def SetDefaults(self, this: c_uint64):
        """``void cGcGalaxyVoxelAttributesData::SetDefaults()``"""
        ...

class cGcGalaxyVoxelGenerator:
    @legacy_hook("cGcGalaxyVoxelGenerator::Populate", static=True)
    def Populate(a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcGalaxyVoxelGenerator::Populate(unsigned __int64, cGcGalaxyVoxelData &, cTkVector3 const&)``"""
        ...

class cGcGameState:
    @legacy_hook("cGcGameState::ComputeWarpCapability")
    def ComputeWarpCapability(self, this: c_uint64, a0: c_float, a1: c_bool, a2: c_uint64, a3: c_uint64) -> c_uint64:
        """``WarpCapabilityResult cGcGameState::ComputeWarpCapability(float, bool, unsigned __int64, cGcGalaxyAttributeGenerator::StarSystemKeyAttributes const&)``"""
        ...
    @legacy_hook("cGcGameState::LoadFromPersistentStorage")
    def LoadFromPersistentStorage(self, this: c_uint64, a0: c_uint64, a1: c_bool) -> c_bool:
        """``bool cGcGameState::LoadFromPersistentStorage(cTkStoragePersistent::Slot, bool)``"""
        ...
    @legacy_hook("cGcGameState::OnSaveProgressCompleted")
    def OnSaveProgressCompleted(self, this: c_uint64, a0: c_bool, a1: c_bool, a2: c_uint64):
        """``void cGcGameState::OnSaveProgressCompleted(bool, bool, GcGameStatePersistence::SpecificSave::Type)``"""
        ...
    @legacy_hook("cGcGameState::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcGameState::Update(float)``"""
        ...
    @legacy_hook("cGcGameState::cGcGameState")
    def cGcGameState(self, this: c_uint64) -> c_uint64:
        """``cGcGameState::cGcGameState()``"""
        ...

class cGcHUD:
    @legacy_hook("cGcHUD::cGcHUD")
    def cGcHUD(self, this: c_uint64) -> c_uint64:
        """``cGcHUD::cGcHUD()``"""
        ...

class cGcHUDManager:
    @legacy_hook("cGcHUDManager::RemoveOSDMessage")
    def RemoveOSDMessage(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cGcHUDManager::cGcHUDManager")
    def cGcHUDManager(self, this: c_uint64) -> c_uint64:
        """``cGcHUDManager::cGcHUDManager()``"""
        ...

class cGcHUDMarker:
    @legacy_hook("cGcHUDMarker::cGcHUDMarker")
    def cGcHUDMarker(self, this: c_uint64) -> c_uint64:
        """``cGcHUDMarker::cGcHUDMarker()``"""
        ...

class cGcInteractionComponent:
    @legacy_hook("cGcInteractionComponent::DoInteractionEvent")
    def DoInteractionEvent(self, this: c_uint64, a0: c_int32):
        """``void cGcInteractionComponent::DoInteractionEvent(eInteractionEvent)``"""
        ...
    @legacy_hook("cGcInteractionComponent::FindFirstTypedComponent", static=True)
    def FindFirstTypedComponent(a0: c_uint64, a1: c_bool) -> c_uint64:
        """``cGcInteractionComponent * cGcInteractionComponent::FindFirstTypedComponent(TkHandle, bool)``"""
        ...
    @legacy_hook("cGcInteractionComponent::GetInteractionData")
    def GetInteractionData(self, this: c_uint64) -> c_uint64:
        """``cGcInteractionData const * cGcInteractionComponent::GetInteractionData()``"""
        ...
    @legacy_hook("cGcInteractionComponent::GetPuzzle")
    def GetPuzzle(self, this: c_uint64) -> c_uint64:
        """``cGcAlienPuzzleEntry const * cGcInteractionComponent::GetPuzzle()``"""
        ...
    @legacy_hook("cGcInteractionComponent::GiveReward")
    def GiveReward(self, this: c_uint64, a0: c_uint64, a1: c_bool, a2: c_bool) -> c_bool:
        """``bool cGcInteractionComponent::GiveReward(cGcAlienPuzzleOption const&, bool, bool)``"""
        ...

class cGcInteractionData:
    @legacy_hook("cGcInteractionData::SetDefaults")
    def SetDefaults(self, this: c_uint64):
        """``void cGcInteractionData::SetDefaults()``"""
        ...

class cGcInventoryStore:
    @legacy_hook("cGcInventoryStore::Add")
    def Add(self, this: c_uint64, a0: c_uint64) -> c_uint64:
        """``cGcInventoryIndex cGcInventoryStore::Add(cGcInventoryElement const&)``"""
        ...
    @legacy_hook("cGcInventoryStore::GetElement")
    def GetElement(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cGcInventoryStore::Remove")
    def Remove(self, this: c_uint64, a0: c_uint64, a1: c_int32) -> c_bool:
        """``bool cGcInventoryStore::Remove(cGcInventoryIndex, int)``"""
        ...
    @legacy_hook("cGcInventoryStore::cGcInventoryStore")
    def cGcInventoryStore(self, this: c_uint64) -> c_uint64:
        """``cGcInventoryStore::cGcInventoryStore()``"""
        ...

class cGcLaserBeam:
    @legacy_hook("cGcLaserBeam::Fire")
    def Fire(self, this: c_uint64, a0: c_bool):
        """``void cGcLaserBeam::Fire(bool)``"""
        ...

class cGcLocalPlayerCharacterInterface:
    @legacy_hook("cGcLocalPlayerCharacterInterface::IsJetpacking")
    def IsJetpacking(self, this: c_uint64) -> c_bool:
        """``bool cGcLocalPlayerCharacterInterface::IsJetpacking()``"""
        ...

class cGcMarkerList:
    @legacy_hook("cGcMarkerList::RemoveMarker")
    def RemoveMarker(self, this: c_uint64, a0: c_uint64) -> c_bool:
        """``bool cGcMarkerList::RemoveMarker(cGcMarkerPoint &)``"""
        ...
    @legacy_hook("cGcMarkerList::TryAddMarker")
    def TryAddMarker(self, this: c_uint64, a0: c_uint64, a1: c_bool) -> c_bool:
        """``bool cGcMarkerList::TryAddMarker(cGcMarkerPoint const&, bool)``"""
        ...

class cGcMarkerPoint:
    @legacy_hook("cGcMarkerPoint::Reset")
    def Reset(self, this: c_uint64):
        """``void cGcMarkerPoint::Reset()``"""
        ...
    @legacy_hook("cGcMarkerPoint::cGcMarkerPoint")
    def cGcMarkerPoint(self, this: c_uint64) -> c_uint64:
        """``cGcMarkerPoint::cGcMarkerPoint()``"""
        ...

class cGcNGuiElement:
    @legacy_hook("cGcNGuiElement::GetPosition")
    def GetPosition(self, this: c_uint64, a0: c_uint64) -> c_uint64:
        """``cTkVector2 cGcNGuiElement::GetPosition(cGcNGuiElement::PositionType)``"""
        ...
    @legacy_hook("cGcNGuiElement::Render")
    def Render(self, this: c_uint64):
        """``void cGcNGuiElement::Render()``"""
        ...
    @legacy_hook("cGcNGuiElement::SetPosition")
    def SetPosition(self, this: c_uint64, a0: c_uint64, a1: c_uint64):
        """``void cGcNGuiElement::SetPosition(cTkVector2 const&, cGcNGuiElement::PositionType)``"""
        ...

class cGcNGuiLayer:
    @legacy_hook("cGcNGuiLayer::AddElement")
    def AddElement(self, this: c_uint64, a0: c_uint64, a1: c_bool) -> c_uint64:
        """``cGcNGuiElement * cGcNGuiLayer::AddElement(cGcNGuiElement *, bool)``"""
        ...
    @legacy_hook("cGcNGuiLayer::FindElementRecursive")
    def FindElementRecursive(self, this: c_uint64, a0: c_uint64, a1: c_int32) -> c_uint64:
        """``cGcNGuiElement * cGcNGuiLayer::FindElementRecursive(cTkHashedNGuiElement const&, eNGuiGameElementType)``"""
        ...
    @legacy_hook("cGcNGuiLayer::FindTextRecursive")
    def FindTextRecursive(self, this: c_uint64, a0: c_uint64) -> c_uint64:
        """``cGcNGuiText * cGcNGuiLayer::FindTextRecursive(union TkID<128> const&)``"""
        ...
    @legacy_hook("cGcNGuiLayer::GetGraphic")
    def GetGraphic(self, this: c_uint64, a0: c_uint64, a1: c_bool) -> c_uint64:
        """``cGcNGuiGraphic * cGcNGuiLayer::GetGraphic(union TkID<128>, bool)``"""
        ...
    @legacy_hook("cGcNGuiLayer::LoadFromMetadata")
    def LoadFromMetadata(self, this: c_uint64, a0: c_uint64, a1: c_bool):
        """``void cGcNGuiLayer::LoadFromMetadata(char const *, bool)``"""
        ...
    @legacy_hook("cGcNGuiLayer::cGcNGuiLayer")
    def cGcNGuiLayer(self, this: c_uint64) -> c_uint64:
        """``cGcNGuiLayer::cGcNGuiLayer()``"""
        ...

class cGcNGuiNodeInfo:
    @legacy_hook("cGcNGuiNodeInfo::Get")
    def Get(self, this: c_uint64, a0: c_uint64):
        """``void cGcNGuiNodeInfo::Get(TkHandle)``"""
        ...

class cGcNGuiText:
    @legacy_hook("cGcNGuiText::EditElement")
    def EditElement(self, this: c_uint64):
        """``void cGcNGuiText::EditElement()``"""
        ...

class cGcNameGenerator:
    @legacy_hook("cGcNameGenerator::GenerateGalacticRegionName")
    def GenerateGalacticRegionName(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcNameGenerator::GenerateGalacticRegionName(unsigned __int64, cTkFixedString<127,char> &, cTkFixedString<127,char> *)``"""
        ...
    @legacy_hook("cGcNameGenerator::GeneratePlanetName")
    def GeneratePlanetName(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcNameGenerator::GeneratePlanetName(unsigned __int64, cTkFixedString<127,char> &, cTkFixedString<127,char> *)``"""
        ...

class cGcNotificationSequenceStartEvent:
    @legacy_hook("cGcNotificationSequenceStartEvent::DeepInterstellarSearch", static=True)
    def DeepInterstellarSearch(a0: c_uint64) -> c_bool:
        """``bool cGcNotificationSequenceStartEvent::DeepInterstellarSearch(cGcNotificationSequenceStage *)``"""
        ...

class cGcOptionsPageUI:
    @legacy_hook("cGcOptionsPageUI::BeginList")
    def BeginList(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cGcOptionsPageUI::ListOption")
    def ListOption(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cGcOptionsPageUI::QualityOption")
    def QualityOption(self, this: c_uint64):
        ...  # modern signature unknown

class cGcPersistentInteractionBuffer:
    @legacy_hook("cGcPersistentInteractionBuffer::LoadGalacticAddressBuffers")
    def LoadGalacticAddressBuffers(self, this: c_uint64, a0: c_uint64):
        """``void cGcPersistentInteractionBuffer::LoadGalacticAddressBuffers(unsigned __int64 const&)``"""
        ...
    @legacy_hook("cGcPersistentInteractionBuffer::PopulateBufferData")
    def PopulateBufferData(self, this: c_uint64, a0: c_uint64):
        """``void cGcPersistentInteractionBuffer::PopulateBufferData(cGcInteractionBuffer &)``"""
        ...
    @legacy_hook("cGcPersistentInteractionBuffer::SaveInteraction")
    def SaveInteraction(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_bool, a3: c_float):
        """``void cGcPersistentInteractionBuffer::SaveInteraction(cTkVector3 const&, cGcInteractionData const&, bool, float)``"""
        ...

class cGcPersistentInteractionsManager:
    @legacy_hook("cGcPersistentInteractionsManager::LoadGalacticAddressBuffers")
    def LoadGalacticAddressBuffers(self, this: c_uint64, a0: c_uint64):
        """``void cGcPersistentInteractionsManager::LoadGalacticAddressBuffers(unsigned __int64 const&)``"""
        ...
    @legacy_hook("cGcPersistentInteractionsManager::PopulateArrays")
    def PopulateArrays(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64, a4: c_uint64):
        """``void cGcPersistentInteractionsManager::PopulateArrays(cTkFixedArray<cGcInteractionBuffer,11> &, cTkDynamicArray<cGcPersistentBase> &, cTkDynamicArray<cGcMaintenanceContainer> &, cTkDynamicArray<cGcMaintenanceContainer> &, cTkDynamicArray<unsigned __int64> &)``"""
        ...

class cGcPhotoModeUI:
    @legacy_hook("cGcPhotoModeUI::OnRenderScreenshotFinished")
    def OnRenderScreenshotFinished(self, this: c_uint64, a0: c_uint64):
        """``void cGcPhotoModeUI::OnRenderScreenshotFinished(void *)``"""
        ...

class cGcPlanet:
    @legacy_hook("cGcPlanet::Construct")
    def Construct(self, this: c_uint64, a0: c_int32):
        """``void cGcPlanet::Construct(int)``"""
        ...
    @legacy_hook("cGcPlanet::Generate")
    def Generate(self, this: c_uint64, a0: c_bool, a1: c_uint64, a2: c_uint64, a3: c_uint64):
        """``void cGcPlanet::Generate(bool, cTkVector3 const&, cGcDiscoveryData const&, cGcPlanetGenerationInputData const&)``"""
        ...
    @legacy_hook("cGcPlanet::SetupRegionMap")
    def SetupRegionMap(self, this: c_uint64):
        """``void cGcPlanet::SetupRegionMap()``"""
        ...
    @legacy_hook("cGcPlanet::UpdateClouds")
    def UpdateClouds(self, this: c_uint64, a0: c_float):
        """``void cGcPlanet::UpdateClouds(float)``"""
        ...
    @legacy_hook("cGcPlanet::UpdateGravity")
    def UpdateGravity(self, this: c_uint64, a0: c_float):
        """``void cGcPlanet::UpdateGravity(float)``"""
        ...
    @legacy_hook("cGcPlanet::UpdateWeather")
    def UpdateWeather(self, this: c_uint64, a0: c_float):
        """``void cGcPlanet::UpdateWeather(float)``"""
        ...
    @legacy_hook("cGcPlanet::cGcPlanet")
    def cGcPlanet(self, this: c_uint64) -> c_uint64:
        """``cGcPlanet::cGcPlanet()``"""
        ...

class cGcPlanetGenerationInputData:
    @legacy_hook("cGcPlanetGenerationInputData::SetDefaults")
    def SetDefaults(self, this: c_uint64):
        """``void cGcPlanetGenerationInputData::SetDefaults()``"""
        ...

class cGcPlanetGenerator:
    @legacy_hook("cGcPlanetGenerator::FillCreatureSpawnDataFromDescription")
    def FillCreatureSpawnDataFromDescription(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcPlanetGenerator::FillCreatureSpawnDataFromDescription(cGcCreatureRoleData const&, cGcCreatureSpawnData &, cGcPlanetData &)``"""
        ...
    @legacy_hook("cGcPlanetGenerator::Generate")
    def Generate(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcPlanetGenerator::Generate(cGcPlanetData &, cGcPlanetGenerationInputData const&, cGcPlanet *)``"""
        ...
    @legacy_hook("cGcPlanetGenerator::GenerateCreatureInfo")
    def GenerateCreatureInfo(self, this: c_uint64, a0: c_uint64, a1: c_uint64):
        """``void cGcPlanetGenerator::GenerateCreatureInfo(cGcPlanetData &, cGcCreatureRoleData &)``"""
        ...
    @legacy_hook("cGcPlanetGenerator::GenerateCreatureRoles")
    def GenerateCreatureRoles(self, this: c_uint64, a0: c_uint64, a1: c_uint64):
        """``void cGcPlanetGenerator::GenerateCreatureRoles(cGcPlanetData &, unsigned __int64 const&)``"""
        ...
    @legacy_hook("cGcPlanetGenerator::GenerateCreatureSpawnData")
    def GenerateCreatureSpawnData(self, this: c_uint64, a0: c_uint64):
        """``void cGcPlanetGenerator::GenerateCreatureSpawnData(cGcPlanetData &)``"""
        ...
    @legacy_hook("cGcPlanetGenerator::GenerateQueryInfo")
    def GenerateQueryInfo(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_bool):
        """``void cGcPlanetGenerator::GenerateQueryInfo(PlanetGenerationQuery &, cGcPlanetGenerationInputData const&, unsigned __int64, bool)``"""
        ...

class cGcPlayer:
    @legacy_hook("cGcPlayer::CheckFallenThroughFloor")
    def CheckFallenThroughFloor(self, this: c_uint64):
        """``void cGcPlayer::CheckFallenThroughFloor()``"""
        ...
    @legacy_hook("cGcPlayer::GetDominantHand")
    def GetDominantHand(self, this: c_uint64) -> c_int32:
        """``eHand cGcPlayer::GetDominantHand()``"""
        ...
    @legacy_hook("cGcPlayer::OnEnteredCockpit")
    def OnEnteredCockpit(self, this: c_uint64):
        """``void cGcPlayer::OnEnteredCockpit()``"""
        ...
    @legacy_hook("cGcPlayer::Prepare")
    def Prepare(self, this: c_uint64, a0: c_uint64):
        """``void cGcPlayer::Prepare(cGcPlayerController *)``"""
        ...
    @legacy_hook("cGcPlayer::RenderInventoryEditor")
    def RenderInventoryEditor(self, this: c_uint64):
        """``void cGcPlayer::RenderInventoryEditor()``"""
        ...
    @legacy_hook("cGcPlayer::RenderNGui")
    def RenderNGui(self, this: c_uint64):
        """``void cGcPlayer::RenderNGui()``"""
        ...
    @legacy_hook("cGcPlayer::SetToPosition")
    def SetToPosition(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcPlayer::SetToPosition(cTkPhysRelVec3 const&, cTkVector3 const&, cTkVector3 const&)``"""
        ...
    @legacy_hook("cGcPlayer::TakeDamage")
    def TakeDamage(self, this: c_uint64, a0: c_float, a1: c_int32, a2: c_uint64, a3: c_uint64, a4: c_uint64, a5: c_uint64):
        """``void cGcPlayer::TakeDamage(float, eDamageType, union TkID<128> const&, cTkVector3 const&, cGcOwnerConcept *, std::vector<cGcCombatEffectDamageMultiplier,TkSTLAllocatorShim<cGcCombatEffectDamageMultiplier,4,-1> > const&)``"""
        ...
    @legacy_hook("cGcPlayer::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcPlayer::Update(float)``"""
        ...
    @legacy_hook("cGcPlayer::UpdateGraphics")
    def UpdateGraphics(self, this: c_uint64, a0: c_bool):
        """``void cGcPlayer::UpdateGraphics(bool)``"""
        ...

class cGcPlayerBasePersistentBuffer:
    @legacy_hook("cGcPlayerBasePersistentBuffer::LoadGalacticAddress")
    def LoadGalacticAddress(self, this: c_uint64, a0: c_uint64, a1: c_uint64):
        """``void cGcPlayerBasePersistentBuffer::LoadGalacticAddress(unsigned __int64 const&, BaseIndex)``"""
        ...

class cGcPlayerCharacterComponent:
    @legacy_hook("cGcPlayerCharacterComponent::SetDeathState")
    def SetDeathState(self, this: c_uint64):
        """``void cGcPlayerCharacterComponent::SetDeathState()``"""
        ...
    @legacy_hook("cGcPlayerCharacterComponent::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcPlayerCharacterComponent::Update(float)``"""
        ...

class cGcPlayerCommunicator:
    @legacy_hook("cGcPlayerCommunicator::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcPlayerCommunicator::Update(float)``"""
        ...

class cGcPlayerCreatureOwnership:
    @legacy_hook("cGcPlayerCreatureOwnership::cGcPlayerCreatureOwnership")
    def cGcPlayerCreatureOwnership(self, this: c_uint64):
        ...  # modern signature unknown

class cGcPlayerDiscoveryHelper:
    @legacy_hook("cGcPlayerDiscoveryHelper::GetDiscoveryWorth")
    def GetDiscoveryWorth(self, this: c_uint64, a0: c_uint64) -> c_int32:
        """``int cGcPlayerDiscoveryHelper::GetDiscoveryWorth(cGcDiscoveryData const&)``"""
        ...

class cGcPlayerEnvironment:
    @legacy_hook("cGcPlayerEnvironment::IsOnPlanet")
    def IsOnPlanet(self, this: c_uint64) -> c_bool:
        """``bool cGcPlayerEnvironment::IsOnPlanet()``"""
        ...
    @legacy_hook("cGcPlayerEnvironment::IsOnboardOwnFreighter")
    def IsOnboardOwnFreighter(self, this: c_uint64) -> c_bool:
        """``bool cGcPlayerEnvironment::IsOnboardOwnFreighter()``"""
        ...
    @legacy_hook("cGcPlayerEnvironment::Update")
    def Update(self, this: c_uint64):
        ...  # modern signature unknown

class cGcPlayerExperienceDirector:
    @legacy_hook("cGcPlayerExperienceDirector::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcPlayerExperienceDirector::Update(float)``"""
        ...

class cGcPlayerFleetManager:
    @legacy_hook("cGcPlayerFleetManager::cGcPlayerFleetManager")
    def cGcPlayerFleetManager(self, this: c_uint64):
        ...  # modern signature unknown

class cGcPlayerFreighterOwnership:
    @legacy_hook("cGcPlayerFreighterOwnership::ResetPlayerFreighterBase")
    def ResetPlayerFreighterBase(self, this: c_uint64) -> c_bool:
        """``bool cGcPlayerFreighterOwnership::ResetPlayerFreighterBase()``"""
        ...
    @legacy_hook("cGcPlayerFreighterOwnership::cGcPlayerFreighterOwnership")
    def cGcPlayerFreighterOwnership(self, this: c_uint64):
        ...  # modern signature unknown

class cGcPlayerHUD:
    @legacy_hook("cGcPlayerHUD::LoadData")
    def LoadData(self, this: c_uint64):
        """``void cGcPlayerHUD::LoadData()``"""
        ...
    @legacy_hook("cGcPlayerHUD::RenderCrosshair")
    def RenderCrosshair(self, this: c_uint64):
        """``void cGcPlayerHUD::RenderCrosshair()``"""
        ...
    @legacy_hook("cGcPlayerHUD::RenderIndicatorPanel")
    def RenderIndicatorPanel(self, this: c_uint64):
        """``void cGcPlayerHUD::RenderIndicatorPanel()``"""
        ...
    @legacy_hook("cGcPlayerHUD::RenderWeaponPanel")
    def RenderWeaponPanel(self, this: c_uint64):
        """``void cGcPlayerHUD::RenderWeaponPanel()``"""
        ...
    @legacy_hook("cGcPlayerHUD::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcPlayerHUD::Update(float)``"""
        ...
    @legacy_hook("cGcPlayerHUD::cGcPlayerHUD")
    def cGcPlayerHUD(self, this: c_uint64) -> c_uint64:
        """``cGcPlayerHUD::cGcPlayerHUD()``"""
        ...

class cGcPlayerMultitoolOwnership:
    @legacy_hook("cGcPlayerMultitoolOwnership::cGcPlayerMultitoolOwnership")
    def cGcPlayerMultitoolOwnership(self, this: c_uint64):
        ...  # modern signature unknown

class cGcPlayerNotifications:
    @legacy_hook("cGcPlayerNotifications::AddTimedMessage")
    def AddTimedMessage(self, this: c_uint64, a0: c_uint64, a1: c_float, a2: c_uint64, a3: c_uint32, a4: c_uint64, a5: c_bool, a6: c_float, a7: c_bool):
        """``void cGcPlayerNotifications::AddTimedMessage(char const *, float, cTkColour const&, unsigned int, cTkSmartResHandle const&, bool, float, bool)``"""
        ...

class cGcPlayerShipOwnership:
    @legacy_hook("cGcPlayerShipOwnership::DestroyShip")
    def DestroyShip(self, this: c_uint64, a0: c_int32) -> c_bool:
        """``bool cGcPlayerShipOwnership::DestroyShip(int)``"""
        ...
    @legacy_hook("cGcPlayerShipOwnership::GetShipComponent")
    def GetShipComponent(self, this: c_uint64, a0: c_int32) -> c_uint64:
        """``cGcSpaceshipComponent const * cGcPlayerShipOwnership::GetShipComponent(int)``"""
        ...
    @legacy_hook("cGcPlayerShipOwnership::SpawnNewShip")
    def SpawnNewShip(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_int32, a3: c_bool) -> c_bool:
        """``bool cGcPlayerShipOwnership::SpawnNewShip(cTkMatrix34 const&, cGcPlayerShipOwnership::ShipSpawnLandingGearState, int, bool)``"""
        ...
    @legacy_hook("cGcPlayerShipOwnership::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcPlayerShipOwnership::Update(float)``"""
        ...
    @legacy_hook("cGcPlayerShipOwnership::UpdateMeshRefresh")
    def UpdateMeshRefresh(self, this: c_uint64):
        """``void cGcPlayerShipOwnership::UpdateMeshRefresh()``"""
        ...
    @legacy_hook("cGcPlayerShipOwnership::cGcPlayerShipOwnership")
    def cGcPlayerShipOwnership(self, this: c_uint64) -> c_uint64:
        """``cGcPlayerShipOwnership::cGcPlayerShipOwnership()``"""
        ...

class cGcPlayerState:
    @legacy_hook("cGcPlayerState::AwardNanites")
    def AwardNanites(self, this: c_uint64, a0: c_int32) -> c_uint32:
        """``unsigned int cGcPlayerState::AwardNanites(int)``"""
        ...
    @legacy_hook("cGcPlayerState::AwardUnits")
    def AwardUnits(self, this: c_uint64, a0: c_int32) -> c_uint32:
        """``unsigned int cGcPlayerState::AwardUnits(int)``"""
        ...
    @legacy_hook("cGcPlayerState::GetStatValue")
    def GetStatValue(self, this: c_uint64, a0: c_int32, a1: c_uint64, a2: c_int32, a3: c_bool, a4: c_bool, a5: c_uint64, a6: c_uint64) -> c_float:
        """``float cGcPlayerState::GetStatValue(eStatsType, ItemLookupType, eStatsType, bool, bool, cGcInventoryStore const *, cGcInventoryStore const *)``"""
        ...
    @legacy_hook("cGcPlayerState::LoadFromData")
    def LoadFromData(self, this: c_uint64, a0: c_uint64, a1: c_bool, a2: c_bool):
        """``void cGcPlayerState::LoadFromData(cGcPlayerStateData const&, bool, bool)``"""
        ...
    @legacy_hook("cGcPlayerState::SaveToData")
    def SaveToData(self, this: c_uint64, a0: c_uint64):
        """``void cGcPlayerState::SaveToData(cGcPlayerStateData &)``"""
        ...
    @legacy_hook("cGcPlayerState::StoreCurrentSystemSpaceStationEndpoint")
    def StoreCurrentSystemSpaceStationEndpoint(self, this: c_uint64):
        """``void cGcPlayerState::StoreCurrentSystemSpaceStationEndpoint()``"""
        ...
    @legacy_hook("cGcPlayerState::cGcPlayerState")
    def cGcPlayerState(self, this: c_uint64) -> c_uint64:
        """``cGcPlayerState::cGcPlayerState()``"""
        ...

class cGcPlayerVehicleOwnership:
    @legacy_hook("cGcPlayerVehicleOwnership::cGcPlayerVehicleOwnership")
    def cGcPlayerVehicleOwnership(self, this: c_uint64) -> c_uint64:
        """``cGcPlayerVehicleOwnership::cGcPlayerVehicleOwnership()``"""
        ...

class cGcPlayerWanted:
    @legacy_hook("cGcPlayerWanted::Update")
    def Update(self, this: c_uint64, a0: c_uint64, a1: c_float):
        """``void cGcPlayerWanted::Update(cTkVector3 const&, float)``"""
        ...

class cGcPlayerWeapon:
    @legacy_hook("cGcPlayerWeapon::GetChargeFactor")
    def GetChargeFactor(self, this: c_uint64) -> c_float:
        """``float cGcPlayerWeapon::GetChargeFactor()``"""
        ...
    @legacy_hook("cGcPlayerWeapon::GetChargeTime")
    def GetChargeTime(self, this: c_uint64) -> c_float:
        """``float cGcPlayerWeapon::GetChargeTime()``"""
        ...

class cGcPositionMarker:
    @legacy_hook("cGcPositionMarker::Render")
    def Render(self, this: c_uint64):
        """``void cGcPositionMarker::Render()``"""
        ...

class cGcPurchaseableItem:
    @legacy_hook("cGcPurchaseableItem::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcPurchaseableItem::Update(float)``"""
        ...

class cGcQuickActionMenu:
    @legacy_hook("cGcQuickActionMenu::TriggerAction")
    def TriggerAction(self, this: c_uint64, a0: c_uint64, a1: c_bool) -> c_bool:
        """``bool cGcQuickActionMenu::TriggerAction(MenuAction const&, bool)``"""
        ...

class cGcQuickMenu:
    @legacy_hook("cGcQuickMenu::cGcQuickMenu")
    def cGcQuickMenu(self, this: c_uint64) -> c_uint64:
        """``cGcQuickMenu::cGcQuickMenu()``"""
        ...

class cGcRealityManager:
    @legacy_hook("cGcRealityManager::Construct")
    def Construct(self, this: c_uint64):
        """``void cGcRealityManager::Construct()``"""
        ...
    @legacy_hook("cGcRealityManager::GenerateProceduralProduct")
    def GenerateProceduralProduct(self, this: c_uint64, a0: c_uint64) -> c_uint64:
        """``cGcProductData const * cGcRealityManager::GenerateProceduralProduct(union TkID<128> const&)``"""
        ...
    @legacy_hook("cGcRealityManager::GenerateProceduralTechnology")
    def GenerateProceduralTechnology(self, this: c_uint64, a0: c_uint64, a1: c_bool) -> c_uint64:
        """``cGcTechnology const * cGcRealityManager::GenerateProceduralTechnology(union TkID<128> const&, bool)``"""
        ...
    @legacy_hook("cGcRealityManager::cGcRealityManager")
    def cGcRealityManager(self, this: c_uint64) -> c_uint64:
        """``cGcRealityManager::cGcRealityManager()``"""
        ...

class cGcResourceCustomisation:
    @legacy_hook("cGcResourceCustomisation::CreateGenerationTask")
    def CreateGenerationTask(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_bool) -> c_uint64:
        """``cGcProceduralTextureManager::TaskContext * cGcResourceCustomisation::CreateGenerationTask(cTkSmartResHandle *, char const *, bool)``"""
        ...

class cGcRewardManager:
    @legacy_hook("cGcRewardManager::GiveGenericReward")
    def GiveGenericReward(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_bool, a4: c_bool, a5: c_uint64, a6: c_bool, a7: c_uint64, a8: c_bool) -> c_bool:
        """``bool cGcRewardManager::GiveGenericReward(union TkID<128> const&, union TkID<128> const&, cTkSeed const&, bool, bool, int &, bool, InventoryChoice, bool)``"""
        ...

class cGcScanEvent:
    @legacy_hook("cGcScanEvent::CalculateMarkerPosition")
    def CalculateMarkerPosition(self, this: c_uint64):
        """``void cGcScanEvent::CalculateMarkerPosition()``"""
        ...
    @legacy_hook("cGcScanEvent::Construct")
    def Construct(self, this: c_uint64, a0: c_int32, a1: c_uint64, a2: c_uint64, a3: c_float, a4: c_bool, a5: c_uint64, a6: c_uint64):
        """``void cGcScanEvent::Construct(eScanTable, cGcScanEventData *, cGcBuilding *, float, bool, std::pair<union TkID<128>,cTkSeed> *, union TkID<128>)``"""
        ...
    @legacy_hook("cGcScanEvent::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcScanEvent::Update(float)``"""
        ...
    @legacy_hook("cGcScanEvent::UpdateInteraction")
    def UpdateInteraction(self, this: c_uint64):
        """``void cGcScanEvent::UpdateInteraction()``"""
        ...
    @legacy_hook("cGcScanEvent::UpdateSpaceStationLocation")
    def UpdateSpaceStationLocation(self, this: c_uint64):
        """``void cGcScanEvent::UpdateSpaceStationLocation()``"""
        ...

class cGcScanEventManager:
    @legacy_hook("cGcScanEventManager::PassesPlanetInfoChecks", static=True)
    def PassesPlanetInfoChecks(a0: c_uint64, a1: c_uint64, a2: c_bool, a3: c_int32, a4: c_bool) -> c_bool:
        """``bool cGcScanEventManager::PassesPlanetInfoChecks(PlanetGenerationQuery const&, cGcScanEventSolarSystemLookup const&, bool, eBuildingClass, bool)``"""
        ...

class cGcShipHUD:
    @legacy_hook("cGcShipHUD::LoadData")
    def LoadData(self, this: c_uint64):
        """``void cGcShipHUD::LoadData()``"""
        ...
    @legacy_hook("cGcShipHUD::ReadPlanetStats")
    def ReadPlanetStats(self, this: c_uint64, a0: c_bool, a1: c_uint64, a2: c_uint64, a3: c_uint64, a4: c_bool, a5: c_uint64, a6: c_uint64):
        """``void cGcShipHUD::ReadPlanetStats(bool, cTkFixedString<512,char> &, cTkFixedString<512,char> &, cTkFixedString<512,char> &, bool, bool &, float *)``"""
        ...
    @legacy_hook("cGcShipHUD::RenderHeadsUp")
    def RenderHeadsUp(self, this: c_uint64):
        """``void cGcShipHUD::RenderHeadsUp()``"""
        ...
    @legacy_hook("cGcShipHUD::cGcShipHUD")
    def cGcShipHUD(self, this: c_uint64) -> c_uint64:
        """``cGcShipHUD::cGcShipHUD()``"""
        ...

class cGcSimpleInteractionComponent:
    @legacy_hook("cGcSimpleInteractionComponent::DoAction")
    def DoAction(self, this: c_uint64):
        """``void cGcSimpleInteractionComponent::DoAction()``"""
        ...

class cGcSimulation:
    @legacy_hook("cGcSimulation::Construct")
    def Construct(self, this: c_uint64):
        """``void cGcSimulation::Construct()``"""
        ...
    @legacy_hook("cGcSimulation::Update")
    def Update(self, this: c_uint64, a0: c_uint64, a1: c_float):
        """``void cGcSimulation::Update(SimulationUpdateMode, float)``"""
        ...
    @legacy_hook("cGcSimulation::cGcSimulation")
    def cGcSimulation(self, this: c_uint64) -> c_uint64:
        """``cGcSimulation::cGcSimulation()``"""
        ...

class cGcSky:
    @legacy_hook("cGcSky::SetStormState")
    def SetStormState(self, this: c_uint64, a0: c_int32):
        """``void cGcSky::SetStormState(cGcSky::eStormState)``"""
        ...
    @legacy_hook("cGcSky::SetSunAngle")
    def SetSunAngle(self, this: c_uint64, a0: c_float):
        """``void cGcSky::SetSunAngle(float)``"""
        ...
    @legacy_hook("cGcSky::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcSky::Update(float)``"""
        ...
    @legacy_hook("cGcSky::UpdateSunPosition")
    def UpdateSunPosition(self, this: c_uint64):
        """``void cGcSky::UpdateSunPosition()``"""
        ...

class cGcSolarSystem:
    @legacy_hook("cGcSolarSystem::Construct")
    def Construct(self, this: c_uint64):
        """``void cGcSolarSystem::Construct()``"""
        ...
    @legacy_hook("cGcSolarSystem::Generate")
    def Generate(self, this: c_uint64, a0: c_bool, a1: c_uint64):
        """``void cGcSolarSystem::Generate(bool, cTkSeed)``"""
        ...
    @legacy_hook("cGcSolarSystem::OnEnterPlanetOrbit")
    def OnEnterPlanetOrbit(self, this: c_uint64, a0: c_bool):
        """``void cGcSolarSystem::OnEnterPlanetOrbit(bool)``"""
        ...
    @legacy_hook("cGcSolarSystem::OnLeavePlanetOrbit")
    def OnLeavePlanetOrbit(self, this: c_uint64, a0: c_bool):
        """``void cGcSolarSystem::OnLeavePlanetOrbit(bool)``"""
        ...
    @legacy_hook("cGcSolarSystem::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcSolarSystem::Update(float)``"""
        ...
    @legacy_hook("cGcSolarSystem::cGcSolarSystem")
    def cGcSolarSystem(self, this: c_uint64) -> c_uint64:
        """``cGcSolarSystem::cGcSolarSystem()``"""
        ...

class cGcSolarSystemGenerator:
    @legacy_hook("cGcSolarSystemGenerator::GenerateBasics")
    def GenerateBasics(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64):
        """``void cGcSolarSystemGenerator::GenerateBasics(cTkSeed const&, cGcGalaxyAttributesAtAddress const&, cGcGalaxyAttributeGenerator::StarSystemKeyAttributes &, cGcSolarSystemGenerator::GenerationData &)``"""
        ...
    @legacy_hook("cGcSolarSystemGenerator::GeneratePlanetBiomes")
    def GeneratePlanetBiomes(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcSolarSystemGenerator::GeneratePlanetBiomes(cGcGalaxyAttributesAtAddress const&, cGcSolarSystemGenerator::GenerationData &, cGcGalaxyAttributeGenerator::StarSystemKeyAttributes &)``"""
        ...
    @legacy_hook("cGcSolarSystemGenerator::GeneratePlanetPositions")
    def GeneratePlanetPositions(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcSolarSystemGenerator::GeneratePlanetPositions(cGcGalaxyAttributesAtAddress const&, cGcSolarSystemGenerator::GenerationData &, cGcSolarSystemGeometry *)``"""
        ...
    @legacy_hook("cGcSolarSystemGenerator::GenerateQueryInfo")
    def GenerateQueryInfo(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cGcSolarSystemGenerator::GenerateQueryInfo(cTkSeed const&, cGcGalaxyAttributesAtAddress const&, cGcSolarSystemGenerator::GenerationData &)``"""
        ...

class cGcSolarSystemQuery:
    @legacy_hook("cGcSolarSystemQuery::Run")
    def Run(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_bool):
        """``void cGcSolarSystemQuery::Run(unsigned __int64, cGcSolarSystemQuery::Type, bool)``"""
        ...

class cGcSpaceshipComponent:
    @legacy_hook("cGcSpaceshipComponent::Eject")
    def Eject(self, this: c_uint64, a0: c_uint64, a1: c_bool, a2: c_bool):
        """``void cGcSpaceshipComponent::Eject(cGcPlayer *, bool, bool)``"""
        ...
    @legacy_hook("cGcSpaceshipComponent::GetVelocity")
    def GetVelocity(self, this: c_uint64) -> c_uint64:
        """``cTkVector3 cGcSpaceshipComponent::GetVelocity()``"""
        ...
    @legacy_hook("cGcSpaceshipComponent::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cGcSpaceshipComponent::Update(float)``"""
        ...
    @legacy_hook("cGcSpaceshipComponent::UpdateControlled")
    def UpdateControlled(self, this: c_uint64, a0: c_float):
        """``void cGcSpaceshipComponent::UpdateControlled(float)``"""
        ...

class cGcSpaceshipWarp:
    @legacy_hook("cGcSpaceshipWarp::GetPulseDriveFuelFactor")
    def GetPulseDriveFuelFactor(self, this: c_uint64) -> c_float:
        """``float cGcSpaceshipWarp::GetPulseDriveFuelFactor()``"""
        ...
    @legacy_hook("cGcSpaceshipWarp::UpdatePulseDrive")
    def UpdatePulseDrive(self, this: c_uint64, a0: c_float):
        """``void cGcPlayerExperienceDirector::UpdatePulseEncounters(float)``"""
        ...

class cGcSpaceshipWeapons:
    @legacy_hook("cGcSpaceshipWeapons::GetAverageBarrelPos")
    def GetAverageBarrelPos(self, this: c_uint64) -> c_uint64:
        """``cTkPhysRelVec3 cGcSpaceshipWeapons::GetAverageBarrelPos()``"""
        ...
    @legacy_hook("cGcSpaceshipWeapons::GetCurrentShootPoints")
    def GetCurrentShootPoints(self, this: c_uint64) -> c_uint64:
        """``cGcShootPoint * cGcSpaceshipWeapons::GetCurrentShootPoints()``"""
        ...
    @legacy_hook("cGcSpaceshipWeapons::GetHeatFactor")
    def GetHeatFactor(self, this: c_uint64) -> c_float:
        """``float cGcSpaceshipWeapons::GetHeatFactor()``"""
        ...
    @legacy_hook("cGcSpaceshipWeapons::GetOverheatProgress")
    def GetOverheatProgress(self, this: c_uint64) -> c_float:
        """``float cGcSpaceshipWeapons::GetOverheatProgress()``"""
        ...

class cGcTerrainEditorBeam:
    @legacy_hook("cGcTerrainEditorBeam::ApplyTerrainEditFlatten")
    def ApplyTerrainEditFlatten(self, this: c_uint64, a0: c_uint64, a1: c_uint64) -> c_int32:
        """``int cGcTerrainEditorBeam::ApplyTerrainEditFlatten(sTerrainEditData, cGcProjectileImpact const&)``"""
        ...
    @legacy_hook("cGcTerrainEditorBeam::ApplyTerrainEditStroke")
    def ApplyTerrainEditStroke(self, this: c_uint64, a0: c_uint64, a1: c_uint64) -> c_int32:
        """``int cGcTerrainEditorBeam::ApplyTerrainEditStroke(sTerrainEditData, cGcProjectileImpact const&)``"""
        ...
    @legacy_hook("cGcTerrainEditorBeam::Fire")
    def Fire(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_int32, a4: c_bool) -> c_bool:
        """``bool cGcTerrainEditorBeam::Fire(cTkPhysRelVec3 const&, cTkRigidBody *, cGcOwnerConcept *, eStatsType, bool)``"""
        ...
    @legacy_hook("cGcTerrainEditorBeam::StartEffect")
    def StartEffect(self, this: c_uint64):
        """``void cGcTerrainEditorBeam::StartEffect()``"""
        ...

class cGcTerrainRegionMap:
    @legacy_hook("cGcTerrainRegionMap::Construct")
    def Construct(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_int32, a4: c_int32):
        """``void cGcTerrainRegionMap::Construct(TkHandle, cTkVoxelGeneratorData *, cGcPlanetBuildingData *, int, int)``"""
        ...

class cGcTextChatInput:
    @legacy_hook("cGcTextChatInput::ParseTextForCommands")
    def ParseTextForCommands(self, this: c_uint64, a0: c_uint64):
        """``void cGcTextChatInput::ParseTextForCommands(cTkFixedString<1023,char> const&)``"""
        ...

class cGcTextChatManager:
    @legacy_hook("cGcTextChatManager::Construct")
    def Construct(self, this: c_uint64):
        """``void cGcTextChatManager::Construct()``"""
        ...
    @legacy_hook("cGcTextChatManager::Say")
    def Say(self, this: c_uint64, a0: c_uint64, a1: c_bool):
        """``void cGcTextChatManager::Say(cTkFixedString<1023,char> const&, bool)``"""
        ...

class cGcVibrationManager:
    @legacy_hook("cGcVibrationManager::SendValue")
    def SendValue(self, this: c_uint64, a0: c_uint64, a1: c_float) -> c_bool:
        """``bool cGcVibrationManager::SendValue(union TkID<128> const&, float)``"""
        ...

class cGcVisitedSystemsBuffer:
    @legacy_hook("cGcVisitedSystemsBuffer::VisitNewGalacticAddress")
    def VisitNewGalacticAddress(self, this: c_uint64, a0: c_uint64):
        """``void cGcVisitedSystemsBuffer::VisitNewGalacticAddress(unsigned __int64 const&)``"""
        ...

class cTkAsyncIOManager:
    @legacy_hook("cTkAsyncIOManager::GetOpData", static=True)
    def GetOpData(a0: c_int32, a1: c_bool) -> c_uint64:
        """``void * cTkAsyncIOManager::GetOpData(int, bool)``"""
        ...
    @legacy_hook("cTkAsyncIOManager::GetOpDataSize", static=True)
    def GetOpDataSize(a0: c_int32, a1: c_bool) -> c_int64:
        """``__int64 cTkAsyncIOManager::GetOpDataSize(int, bool)``"""
        ...

class cTkAudioManager:
    @legacy_hook("cTkAudioManager::Play")
    def Play(self, this: c_uint64, a0: c_uint64, a1: c_uint64) -> c_bool:
        """``bool cTkAudioManager::Play(TkAudioID, TkAudioObject)``"""
        ...
    @legacy_hook("cTkAudioManager::Play_attenuated")
    def Play_attenuated(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_float) -> c_bool:
        """``bool cTkAudioManager::Play(TkAudioID, cTkVector3 const&, TkAudioObject, float)``"""
        ...

class cTkDynamicGravityControl:
    @legacy_hook("cTkDynamicGravityControl::Construct")
    def Construct(self, this: c_uint64):
        """``void cTkDynamicGravityControl::Construct()``"""
        ...
    @legacy_hook("cTkDynamicGravityControl::GetGravity")
    def GetGravity(self, this: c_uint64, a0: c_uint64) -> c_uint64:
        """``cTkGravityData cTkDynamicGravityControl::GetGravity(cTkVector3 const&)``"""
        ...
    @legacy_hook("cTkDynamicGravityControl::UpdateGravityPoint")
    def UpdateGravityPoint(self, this: c_uint64, a0: c_uint64, a1: c_float, a2: c_float):
        """``void cTkDynamicGravityControl::UpdateGravityPoint(cTkVector3 const&, float, float)``"""
        ...
    @legacy_hook("cTkDynamicGravityControl::cTkDynamicGravityControl")
    def cTkDynamicGravityControl(self, this: c_uint64) -> c_uint64:
        """``cTkDynamicGravityControl::cTkDynamicGravityControl()``"""
        ...

class cTkEngineUtils:
    @legacy_hook("cTkEngineUtils::GetMasterModelNode", static=True)
    def GetMasterModelNode(a0: c_uint64, a1: c_int32) -> c_uint64:
        """``TkHandle cTkEngineUtils::GetMasterModelNode(TkHandle, eMasterModelNodeDistance)``"""
        ...
    @legacy_hook("cTkEngineUtils::GetMatricesFromNode", static=True)
    def GetMatricesFromNode(a0: c_uint64, a1: c_uint64, a2: c_uint64) -> c_bool:
        """``bool cTkEngineUtils::GetMatricesFromNode(TkHandle, cTkMatrix34 *, cTkMatrix34 *)``"""
        ...
    @legacy_hook("cTkEngineUtils::LoadResourcesFromDisk", static=True)
    def LoadResourcesFromDisk(a0: c_uint64) -> c_uint64:
        """``EngineUtils::LoadResourcesResult EngineUtils::LoadResourcesFromDisk(EngineUtils::LoadResourcesBalancing)``"""
        ...
    @legacy_hook("cTkEngineUtils::RepositionGroupNode", static=True)
    def RepositionGroupNode(a0: c_uint64, a1: c_uint64):
        """``void cTkEngineUtils::RepositionGroupNode(TkHandle, cTkVector3 const&)``"""
        ...

class cTkFSM:
    @legacy_hook("cTkFSM::Construct")
    def Construct(self, this: c_uint64, a0: c_uint64, a1: c_uint64):
        """``void cTkFSM::Construct(cTkFSMStateOffset const *, union TkID<128> const&)``"""
        ...
    @legacy_hook("cTkFSM::StateChange")
    def StateChange(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_bool):
        """``void cTkFSM::StateChange(union TkID<128> const&, void const *, bool)``"""
        ...
    @legacy_hook("cTkFSM::Update")
    def Update(self, this: c_uint64, a0: c_float):
        """``void cTkFSM::Update(float)``"""
        ...

class cTkFSMState:
    @legacy_hook("cTkFSMState::StateChange")
    def StateChange(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_bool):
        """``void cTkFSMState::StateChange(union TkID<128> const&, void const *, bool)``"""
        ...

class cTkFileSystem:
    @legacy_hook("cTkFileSystem::CreatePath")
    def CreatePath(self, this: c_uint64, a0: c_uint64):
        """``void cTkFileSystem::CreatePath(char const *)``"""
        ...
    @legacy_hook("cTkFileSystem::DoesFileExist")
    def DoesFileExist(self, this: c_uint64, a0: c_uint64) -> c_bool:
        """``bool cTkFileSystem::DoesFileExist(char const *)``"""
        ...
    @legacy_hook("cTkFileSystem::EnumerateDirectory")
    def EnumerateDirectory(self, this: c_uint64, a0: c_uint64, a1: c_uint64, a2: c_int32, a3: c_int32) -> c_int32:
        """``int cTkFileSystem::EnumerateDirectory(char const *, char * * const, int, int)``"""
        ...
    @legacy_hook("cTkFileSystem::GetInstance", static=True)
    def GetInstance() -> c_uint64:
        """``cTkFileSystem & cTkFileSystem::GetInstance()``"""
        ...
    @legacy_hook("cTkFileSystem::IsModded")
    def IsModded(self, this: c_uint64) -> c_bool:
        """``bool cTkFileSystem::IsModded()``"""
        ...
    @legacy_hook("cTkFileSystem::LoadModDirectory")
    def LoadModDirectory(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cTkFileSystem::LoadModSubdirectory")
    def LoadModSubdirectory(self, this: c_uint64):
        ...  # modern signature unknown
    @legacy_hook("cTkFileSystem::Open")
    def Open(self, this: c_uint64, a0: c_uint64, a1: c_int32) -> c_uint64:
        """``FIOS2HANDLE * cTkFileSystem::Open(char const *, eFileOpenMode)``"""
        ...
    @legacy_hook("cTkFileSystem::Write")
    def Write(self, this: c_uint64, a0: c_uint64, a1: c_int64, a2: c_int64, a3: c_uint64) -> c_int64:
        """``__int64 cTkFileSystem::Write(void *, __int64, __int64, FIOS2HANDLE *)``"""
        ...

    class Data:
        @legacy_hook("cTkFileSystem::Data::Data")
        def Data(self, this: c_uint64, a0: c_bool, a1: c_bool) -> c_uint64:
            """``cTkFileSystem::Data::Data(bool, bool)``"""
            ...
        @legacy_hook("cTkFileSystem::Data::MountAllArchives")
        def MountAllArchives(self, this: c_uint64):
            ...  # modern signature unknown

class cTkGraphicsAPI:
    @legacy_hook("cTkGraphicsAPI::CreateIndexBuffer", static=True)
    def CreateIndexBuffer(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_int32, a4: c_bool, a5: c_bool) -> c_uint64:
        """``void * cTkGraphicsAPI::CreateIndexBuffer(VkBuffer_T * &, TkDeviceMemory &, void *, int, bool, bool)``"""
        ...
    @legacy_hook("cTkGraphicsAPI::CreateVertexBuffer", static=True)
    def CreateVertexBuffer(a0: c_uint64, a1: c_uint64, a2: c_uint64, a3: c_uint64, a4: c_uint64, a5: c_int32, a6: c_int32, a7: c_bool, a8: c_bool, a9: c_bool) -> c_uint64:
        """``void * cTkGraphicsAPI::CreateVertexBuffer(VkBuffer_T * &, TkDeviceMemory &, void * *, void *, cTkVertexLayoutRT const&, int, int, bool, bool, bool)``"""
        ...
    @legacy_hook("cTkGraphicsAPI::GetVertexBufferData", static=True)
    def GetVertexBufferData(a0: c_uint64, a1: c_uint64, a2: c_uint64):
        """``void cTkGraphicsAPI::GetVertexBufferData(cTkBuffer * const, void *, int *)``"""
        ...

class cTkInputPort:
    @legacy_hook("cTkInputPort::GetButton")
    def GetButton(self, this: c_uint64, a0: c_int32, a1: c_int32, a2: c_bool) -> c_bool:
        """``bool cTkInputPort::GetButton(eInputButton, eInputValidation, bool)``"""
        ...
    @legacy_hook("cTkInputPort::SetButton")
    def SetButton(self, this: c_uint64, a0: c_int32):
        """``void cTkInputPort::SetButton(eInputButton)``"""
        ...

class cTkLanguageManager:
    @legacy_hook("cTkLanguageManager::GetInstance", static=True)
    def GetInstance() -> c_uint64:
        """``cTkLanguageManager & cTkLanguageManager::GetInstance()``"""
        ...

class cTkLanguageManagerBase:
    @legacy_hook("cTkLanguageManagerBase::Load")
    def Load(self, this: c_uint64):
        """``void cTkLanguageManagerBase::Load()``"""
        ...
    @legacy_hook("cTkLanguageManagerBase::Translate")
    def Translate(self, this: c_uint64, a0: c_uint64, a1: c_uint64) -> c_uint64:
        """``char const * cTkLanguageManagerBase::Translate(char const *, char const *)``"""
        ...

class cTkMemoryManager:
    @legacy_hook("cTkMemoryManager::Free")
    def Free(self, this: c_uint64, a0: c_uint64, a1: c_int32):
        """``void cTkMemoryManager::Free(void *, int)``"""
        ...
    @legacy_hook("cTkMemoryManager::Malloc")
    def Malloc(self, this: c_uint64, a0: c_int32, a1: c_uint64, a2: c_int32, a3: c_uint64, a4: c_int32, a5: c_int32) -> c_uint64:
        """``void * cTkMemoryManager::Malloc(int, char const *, int, char const *, int, int)``"""
        ...

class cTkMetaDataManager:
    @legacy_hook("cTkMetaDataManager::GetInstance", static=True)
    def GetInstance() -> c_uint64:
        """``cTkMetaDataManager & cTkMetaDataManager::GetInstance()``"""
        ...
    @legacy_hook("cTkMetaDataManager::LoadModdedData")
    def LoadModdedData(self, this: c_uint64):
        ...  # modern signature unknown

class cTkMetaDataXML:
    @legacy_hook("cTkMetaDataXML::GetLookup", static=True)
    def GetLookup(a0: c_uint64) -> c_uint64:
        """``cTkMetaDataXMLFunctionLookup * cTkMetaDataXML::GetLookup(char const *)``"""
        ...
    @legacy_hook("cTkMetaDataXML::Register", static=True)
    def Register(a0: c_uint64, a1: c_uint64) -> c_uint64:
        """``void cTkMetaDataXML::Register(char const *,void (__cdecl*)(cTkClassPointer const &,XMLNode &,bool),void (__cdecl*)(cTkClassPointer &,XMLNode &,cTkLinearMemoryPool *),bool (__cdecl*)(cTkClassPointer const&, char const *))``"""
        ...

class cTkResource:
    @legacy_hook("cTkResource::cTkResource")
    def cTkResource(self, this: c_uint64, a0: c_int32, a1: c_uint64, a2: c_int32) -> c_uint64:
        """``cTkResource::cTkResource(int, std::basic_string<char,std::char_traits<char>,TkSTLAllocatorShim<char,1,-1> > const&, int)``"""
        ...

class cTkResourceManager:
    @legacy_hook("cTkResourceManager::AddResource")
    def AddResource(self, this: c_uint64, a0: c_int32, a1: c_uint64, a2: c_int32, a3: c_bool, a4: c_uint64) -> c_uint64:
        """``cTkSmartResHandle cTkResourceManager::AddResource(int, char const *, int, bool, cTkResourceDescriptor *)``"""
        ...
    @legacy_hook("cTkResourceManager::FindResourceA")
    def FindResourceA(self, this: c_uint64, a0: c_int32, a1: c_uint64, a2: c_uint64, a3: c_bool, a4: c_bool) -> c_uint64:
        """``cTkResource * cTkResourceManager::FindResourceA(int, char const *, cTkResourceDescriptor const *, bool, bool)``"""
        ...
    @legacy_hook("cTkResourceManager::GetDefaultResource")
    def GetDefaultResource(self, this: c_uint64, a0: c_int32, a1: c_int32) -> c_uint64:
        """``cTkResource * cTkResourceManager::GetDefaultResource(int, int)``"""
        ...

class cTkRigidBody:
    @legacy_hook("cTkRigidBody::SetAngularVelocity")
    def SetAngularVelocity(self, this: c_uint64, a0: c_uint64):
        """``void cTkRigidBody::SetAngularVelocity(cTkVector3 const&)``"""
        ...
    @legacy_hook("cTkRigidBody::SetLinearVelocity")
    def SetLinearVelocity(self, this: c_uint64, a0: c_uint64):
        """``void cTkRigidBody::SetLinearVelocity(cTkVector3 const&)``"""
        ...

class cTkStopwatch:
    @legacy_hook("cTkStopwatch::GetDurationInSeconds")
    def GetDurationInSeconds(self, this: c_uint64) -> c_float:
        """``float cTkStopwatch::GetDurationInSeconds()``"""
        ...

class cTkSystem:
    @legacy_hook("cTkSystem::GetInstance", static=True)
    def GetInstance() -> c_uint64:
        """``cTkSystem & cTkSystem::GetInstance()``"""
        ...
    @legacy_hook("cTkSystem::IntegratedGPUActive")
    def IntegratedGPUActive(self, this: c_uint64) -> c_bool:
        """``bool cTkSystem::IntegratedGPUActive()``"""
        ...

class cTkTexture:
    @legacy_hook("cTkTexture::CopyPixelDataToBuffer")
    def CopyPixelDataToBuffer(self, this: c_uint64, a0: c_uint64, a1: c_bool, a2: c_uint32, a3: c_uint32):
        """``void cTkTexture::CopyPixelDataToBuffer(char *, bool, unsigned int, unsigned int)``"""
        ...
    @legacy_hook("cTkTexture::CreateEmptyTexture")
    def CreateEmptyTexture(self, this: c_uint64, a0: c_int32, a1: c_uint32, a2: c_uint32, a3: c_uint32, a4: c_uint32, a5: c_uint32, a6: c_int32, a7: c_int32, a8: c_uint32, a9: c_bool, a10: c_bool, a11: c_bool, a12: c_bool, a13: c_bool):
        """``void cTkTexture::CreateEmptyTexture(eTkTextureType, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, eTextureAddressMode, eTextureFilterMode, unsigned int, bool, bool, bool, bool, bool)``"""
        ...

class cTkTextureBase:
    @legacy_hook("cTkTextureBase::CalculateTextureSize", static=True)
    def CalculateTextureSize(a0: c_int32, a1: c_int32, a2: c_int32, a3: c_int32) -> c_uint32:
        """``unsigned int cTkTextureBase::CalculateTextureSize(cTkTextureBase::eTexFormat, int, int, int)``"""
        ...
