"""Generate nmspy/data/generated_hooks.py: the full upstream hook surface, gated.

Emits one hook stub per function upstream NMS.py supported (upstream_data_413.json),
grouped into plain (non-Structure) classes so the hand-written classes in
nmspy/data/types.py can inherit them as mixins. Prototypes come from the 4.13 PDB
dump (parameter types and staticness); C++ pointer/reference/struct arguments map to
raw c_uint64 addresses, floats stay floats so the x64 ABI is respected.

Every stub resolves through legacy_hook, so availability is data-driven from
offsets.json: an address hooks normally, NOT_YET_FOUND / NOT_IN_THIS_VERSION degrade
to a warning DisabledHook.

    python generate_hook_stubs.py          # rewrites nmspy/data/generated_hooks.py
"""

import json
import keyword
import re
from collections import defaultdict
from pathlib import Path

TARGETS = Path(__file__).parent / "upstream_data_413.json"
REF_413 = r"E:\AI_NMS_DISASM\NMS1091_GHIDRA_ANALYSIS\reference_symbol_db.json"
OUTPUT = Path(__file__).parents[2] / "nmspy" / "data" / "generated_hooks.py"

HEADER = '''"""The full hook surface upstream NMS.py supported on 4.13, gated per build.

AUTO-GENERATED by tools/legacy_re/generate_hook_stubs.py -- do not edit by hand.
Prototypes derive from the 4.13 PDB; pointer/reference/struct arguments are raw
c_uint64 addresses. Whether each hook works in the running build is data-driven from
offsets.json (see nmspy.data.offsets.availability): located functions hook normally,
the rest degrade to warning stubs. Hand-written classes in nmspy.data.types inherit
these as mixins and refine them.
"""

from ctypes import c_bool, c_double, c_float, c_int8, c_int16, c_int32, c_int64, c_uint8, c_uint16, c_uint32, c_uint64  # noqa: E501

from nmspy.data.offsets import legacy_hook

'''


def ctype_of(cpp: str):
    t = cpp.replace("const", "").strip()
    if "*" in t or "&" in t:
        return "c_uint64"
    t = re.sub(r"\s+", " ", t)
    table = {
        "float": "c_float",
        "double": "c_double",
        "bool": "c_bool",
        "char": "c_int8",
        "signed char": "c_int8",
        "unsigned char": "c_uint8",
        "short": "c_int16",
        "unsigned short": "c_uint16",
        "int": "c_int32",
        "long": "c_int32",
        "unsigned int": "c_uint32",
        "unsigned long": "c_uint32",
        "__int64": "c_int64",
        "unsigned __int64": "c_uint64",
        "void": None,
    }
    if t in table:
        return table[t]
    if re.fullmatch(r"e\w+", t) or "::e" in t:
        return "c_int32"  # enum
    return "c_uint64"  # by-value struct or anything exotic: raw bits/hidden pointer


def sanitize(name: str, index: int) -> str:
    name = re.sub(r"\W", "_", name or "")
    if not name or keyword.iskeyword(name) or name in ("self", "this"):
        name = f"a{index}"
    return name


def render_stub(upstream_name: str, method_name: str, ref, mangled: str, indent: str) -> str:
    lines = []
    sig = ref.get("signature") if ref else None
    parts = upstream_name.split("::")
    # The mangled name is authoritative: @@YA = namespace/free function, @@SA =
    # static member; both take no `this`. Fall back to a namespace heuristic.
    if "@@YA" in (mangled or "") or "@@SA" in (mangled or ""):
        is_static = True
    elif mangled and mangled.startswith("?"):
        is_static = False
    else:
        is_static = len(parts) == 1 or not parts[0].startswith(("cGc", "cTk", "cEg"))
    params = []
    if ref:
        for i, p in enumerate(ref.get("parameters") or []):
            ct = ctype_of(p.get("type", ""))
            params.append((sanitize(p.get("name"), i), ct or "c_uint64"))
    ret = ctype_of(ref.get("return_type", "void")) if ref else None

    args = [] if is_static else ["self", "this: c_uint64"]
    args += [f"{n}: {t}" for n, t in params]
    ret_ann = f" -> {ret}" if ret else ""
    static_arg = ", static=True" if is_static else ""

    lines.append(f'{indent}@legacy_hook("{upstream_name}"{static_arg})')
    lines.append(f"{indent}def {method_name}({', '.join(args)}){ret_ann}:")
    if sig:
        lines.append(f'{indent}    """``{sig}``"""')
        lines.append(f"{indent}    ...")
    else:
        lines.append(f"{indent}    ...  # modern signature unknown")
    return "\n".join(lines)


def main():
    targets = json.loads(TARGETS.read_text())
    ref_by_mangled = {
        f["name"]: f for f in json.load(open(REF_413))["functions"]
    }

    tree = defaultdict(lambda: defaultdict(list))  # outer -> inner('' = flat) -> stubs
    free = []
    seen = defaultdict(int)
    for entry in sorted(targets, key=lambda e: e["name"]):
        name = entry["name"]
        ref = ref_by_mangled.get(entry["mangled_name"])
        parts = name.split("::")
        method = sanitize(parts[-1], 0)
        seen[name] += 1
        if seen[name] > 1:
            method = f"{method}_{seen[name]}"  # overload; see the mangled name
        mangled = entry.get("mangled_name", "")
        if len(parts) == 1:
            free.append(render_stub(name, method, ref, mangled, ""))
        elif len(parts) == 2:
            tree[parts[0]][""].append(render_stub(name, method, ref, mangled, "    "))
        else:
            tree[parts[0]]["::".join(parts[1:-1])].append(
                render_stub(name, method, ref, mangled, "        ")
            )

    out = [HEADER]
    for stub in free:
        out.append(stub + "\n\n")
    for outer in sorted(tree):
        out.append(f"class {outer}:\n")
        for inner in sorted(tree[outer]):
            if inner:
                out.append(f"    class {sanitize(inner, 0)}:\n")
            for stub in tree[outer][inner]:
                out.append(stub + "\n")
            out.append("\n")
    OUTPUT.write_text("".join(out).rstrip() + "\n", newline="\n")
    n_classes = len(tree)
    n_stubs = sum(len(v) for c in tree.values() for v in c.values()) + len(free)
    print(f"wrote {OUTPUT}: {n_stubs} stubs in {n_classes} classes + {len(free)} free functions")


if __name__ == "__main__":
    main()
